name: Fly Deploy

on:
  push:
    branches: 
      - master
    paths-ignore:
      - 'docker-compose.yml'
      - 'README.md'
  pull_request:
    branches: 
      - master
    paths-ignore:
      - 'docker-compose.yml'
      - 'README.md'

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
